### ISSUE TITLE
How to use with existing traefik install

### ISSUE THREAD

**Issue by czadikem** [sulu5890/searx-traefik-docker#6]
How do I use this with an existing traefik install.  This is how I installed traefik. With this video https://www.youtube.com/watch?v=JYZDzcurX3I using this repository https://github.com/arizonal2014/traefik-as-a-reverse-proxy .

**Comment by sulu5890** [comment]
This wasn't exactly designed to be used that way and more just as a reference for how you could go about setting it up as pretty much a direct translation from Caddy to Traefik from the searx/searx-docker repo.

You can see in docker-compose.yaml how it is set up and adapt that to your setup, however do know that my implementation does have issues and has not been texted on versions of searx beyond 0.18 and there are major issues with it. Frankly I don't have much interest in fixing these issues either as I don't even really use traefik much anymore and made this very quickly for a reddit comment.
